---
name: "CI"

on:
  push:
    branches: ["main"]
  workflow_dispatch: null

permissions:
  contents: "write"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
        with:
          fetch-depth: 0
      - uses: "pnpm/action-setup@v6"
        with:
          version: latest
      - uses: "actions/setup-node@v7"
        with:
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml
            frontend/pnpm-lock.yaml
      - uses: "actions/cache@v6"
        id: "cache-pipx"
        with:
          path: |
            ~/.local/pipx
            ~/.cache/pipx
          key: "${{ runner.os }}-pipx-tools"
          restore-keys: "${{ runner.os }}-pipx-"
      - name: "Install yamlfix"
        run: "pipx install yamlfix"
        if: "steps.cache-pipx.outputs.cache-hit != 'true'"
      - run: "pnpm install --no-frozen-lockfile --ignore-scripts"
      - run: "pnpm run ci"
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A ':!.github/**'
          git diff --cached --quiet || git commit -m "chore: changelog and formatting [skip ci]"
      - run: |-
          git push -f origin main
